// Fonts are set up in the layout.js file

import { Lugrasimo } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const Lugra = Lugrasimo({
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Lugra.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
